### ISSUE TITLE
Back

### ISSUE THREAD

**Issue by meitavelo** [SkylineCommunications/dataminer-docs#844] opened 2022-12-20 12:12 UTC
When a backslash is succeeded by a '[', the result will not include the backslash.

E.G. C:\Skyline DataMiner\Elements\[Element Name])
Result:  C:\Skyline DataMiner\Elements[Element Name])

Proposed solution is to double the backslash

**Comment by MariekeGO** [comment] 2022-12-20 12:23
This is normal behavior in markdown, as the backslash will be interpreted as intended to escape the "[". The best way to circumvent this is to put file paths between backticks ("`"). I noticed that this problem occurs in [NT_UPDATE_PORTS_XML (128)](https://docs.dataminer.services/develop/api/NotifyTypes/NT_UPDATE_PORTS_XML.html?q=NT_UPDATE_PORTS_XML%20(128)), so I'll correct it there. If you spot this anywhere else, let me know.

**Closed** 2022-12-20 13:47 UTC
